In [1]:
# 파일 불러오기
import pandas as pd
df = './data/bccard_201906.csv'
bccard_df = pd.read_csv(df)
bccard_df

,Unnamed: 0,REG_YYMM,MEGA_CTY_NO,MEGA_CTY_NM,CTY_RGN_NO,CTY_RGN_NM,ADMI_CTY_NO,ADMI_CTY_NM,MAIN_BUZ_CODE,MAIN_BUZ_DESC,...,CSTMR_GUBUN,CSTMR_MEGA_CTY_NO,CSTMR_MEGA_CTY_NM,CSTMR_CTY_RGN_NO,CSTMR_CTY_RGN_NM,SEX_CTGO_CD,AGE_VAL,FLC,AMT,CNT
0,0,201906,11,서울특별시,1162,관악구,11620585,낙성대동,80,음식,...,내국인,11,서울특별시,1162,관악구,2,30대,2,26284804,1892
1,1,201906,11,서울특별시,1159,동작구,11590560,상도4동,30,생활,...,내국인,11,서울특별시,1165,서초구,2,20대,1,109290,18
2,2,201906,11,서울특별시,1162,관악구,11620595,청룡동,30,생활,...,내국인,11,서울특별시,1162,관악구,1,20대,1,268850,52
3,3,201906,11,서울특별시,1144,마포구,11440660,서교동,80,음식,...,내국인,11,서울특별시,1138,은평구,1,20대,1,44174450,1790
4,4,201906,11,서울특별시,1120,성동구,11200550,사근동,80,음식,...,내국인,11,서울특별시,1120,성동구,1,20대,1,60338146,3536
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99996,99996,201906,11,서울특별시,1165,서초구,11650520,서초2동,30,생활,...,내국인,43,충청북도,4311,청주시,1,50대,4,50600,10
99997,99997,201906,11,서울특별시,1117,용산구,11170520,용산2가동,30,생활,...,내국인,11,서울특별시,1162,관악구,1,40대,2,38640,7
99998,99998,201906,11,서울특별시,1156,영등포구,11560535,영등포동,30,생활,...,내국인,28,인천광역시,2817,미추홀구,2,30대,2,340590,15
99999,99999,201906,11,서울특별시,1141,서대문구,11410585,신촌동,40,쇼핑,...,내국인,44,충청남도,4413,천안시,1,20대,2,117100,3
100000,100000,201906,11,서울특별시,1135,노원구,11350710,상계9동,20,문화,...,내국인,41,경기도,4115,의정부시,1,40대,3,5227500,7

In [3]:
bccard_df.head() #앞부분 5개 출력

,Unnamed: 0,REG_YYMM,MEGA_CTY_NO,MEGA_CTY_NM,CTY_RGN_NO,CTY_RGN_NM,ADMI_CTY_NO,ADMI_CTY_NM,MAIN_BUZ_CODE,MAIN_BUZ_DESC,...,CSTMR_GUBUN,CSTMR_MEGA_CTY_NO,CSTMR_MEGA_CTY_NM,CSTMR_CTY_RGN_NO,CSTMR_CTY_RGN_NM,SEX_CTGO_CD,AGE_VAL,FLC,AMT,CNT
0,0,201906,11,서울특별시,1162,관악구,11620585,낙성대동,80,음식,...,내국인,11,서울특별시,1162,관악구,2,30대,2,26284804,1892
1,1,201906,11,서울특별시,1159,동작구,11590560,상도4동,30,생활,...,내국인,11,서울특별시,1165,서초구,2,20대,1,109290,18
2,2,201906,11,서울특별시,1162,관악구,11620595,청룡동,30,생활,...,내국인,11,서울특별시,1162,관악구,1,20대,1,268850,52
3,3,201906,11,서울특별시,1144,마포구,11440660,서교동,80,음식,...,내국인,11,서울특별시,1138,은평구,1,20대,1,44174450,1790
4,4,201906,11,서울특별시,1120,성동구,11200550,사근동,80,음식,...,내국인,11,서울특별시,1120,성동구,1,20대,1,60338146,3536

In [4]:
bccard_df.tail() #뒷부분 5개 출력

,Unnamed: 0,REG_YYMM,MEGA_CTY_NO,MEGA_CTY_NM,CTY_RGN_NO,CTY_RGN_NM,ADMI_CTY_NO,ADMI_CTY_NM,MAIN_BUZ_CODE,MAIN_BUZ_DESC,...,CSTMR_GUBUN,CSTMR_MEGA_CTY_NO,CSTMR_MEGA_CTY_NM,CSTMR_CTY_RGN_NO,CSTMR_CTY_RGN_NM,SEX_CTGO_CD,AGE_VAL,FLC,AMT,CNT
99996,99996,201906,11,서울특별시,1165,서초구,11650520,서초2동,30,생활,...,내국인,43,충청북도,4311,청주시,1,50대,4,50600,10
99997,99997,201906,11,서울특별시,1117,용산구,11170520,용산2가동,30,생활,...,내국인,11,서울특별시,1162,관악구,1,40대,2,38640,7
99998,99998,201906,11,서울특별시,1156,영등포구,11560535,영등포동,30,생활,...,내국인,28,인천광역시,2817,미추홀구,2,30대,2,340590,15
99999,99999,201906,11,서울특별시,1141,서대문구,11410585,신촌동,40,쇼핑,...,내국인,44,충청남도,4413,천안시,1,20대,2,117100,3
100000,100000,201906,11,서울특별시,1135,노원구,11350710,상계9동,20,문화,...,내국인,41,경기도,4115,의정부시,1,40대,3,5227500,7

In [45]:
len(bccard_df), bccard_df.shape # len(bccard_df) : 전체 데이터의 행(줄)수 확인, 
                                # bccard_df.shape : 전체 데이터의 (행, 열) 모양 확인

(100001, (100001, 24))

In [51]:
seoul_df = bccard_df[bccard_df['CSTMR_MEGA_CTY_NM'] == '서울특별시'] # 서울 거주지와 비거주지 데이터로 나누기
other_df = bccard_df[bccard_df['CSTMR_MEGA_CTY_NM'] != '서울특별시']
len(seoul_df) # 서울 거주 고객수

54150

In [50]:
seoul_df['AMT'].sum() # 서울 거주 총 소비액

np.int64(119663142676)

In [49]:
seoul_df['CNT'].sum() # 서울 거주 카드 이용건수

np.int64(5542462)

In [48]:
len(other_df) # 서울 비거주 고객수

45851

In [46]:
other_df['AMT'].sum() # 서울 비거주 총 소비액

np.int64(146587135822)

In [47]:
other_df['CNT'].sum() # 서울 비거주 카드 이용건수

np.int64(4950200)

In [72]:
cvs_df = bccard_df[bccard_df['TP_BUZ_NO'] == 4010] # 편의점(4010) 데이터만 추출
cvs_df

,Unnamed: 0,REG_YYMM,MEGA_CTY_NO,MEGA_CTY_NM,CTY_RGN_NO,CTY_RGN_NM,ADMI_CTY_NO,ADMI_CTY_NM,MAIN_BUZ_CODE,MAIN_BUZ_DESC,...,CSTMR_GUBUN,CSTMR_MEGA_CTY_NO,CSTMR_MEGA_CTY_NM,CSTMR_CTY_RGN_NO,CSTMR_CTY_RGN_NM,SEX_CTGO_CD,AGE_VAL,FLC,AMT,CNT
1,1,201906,11,서울특별시,1159,동작구,11590560,상도4동,30,생활,...,내국인,11,서울특별시,1165,서초구,2,20대,1,109290,18
6,6,201906,11,서울특별시,1168,강남구,11680521,논현1동,30,생활,...,내국인,11,서울특별시,1150,강서구,2,20대,1,1461800,274
12,12,201906,11,서울특별시,1168,강남구,11680545,압구정동,30,생활,...,내국인,11,서울특별시,1168,강남구,1,30대,3,230730,34
16,16,201906,11,서울특별시,1138,은평구,11380690,진관동,30,생활,...,내국인,11,서울특별시,1138,은평구,1,20대,2,1087940,154
19,19,201906,11,서울특별시,1174,강동구,11740685,길동,30,생활,...,내국인,11,서울특별시,1171,송파구,1,40대,3,2569590,361
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99982,99982,201906,11,서울특별시,1121,광진구,11215710,화양동,30,생활,...,내국인,41,경기도,4182,가평군,1,60대 이상,5,69940,6
99991,99991,201906,11,서울특별시,1174,강동구,11740550,고덕1동,30,생활,...,내국인,41,경기도,4136,남양주시,2,40대,3,68980,15
99993,99993,201906,11,서울특별시,1132,도봉구,11320514,창4동,30,생활,...,내국인,41,경기도,4117,안양시,2,40대,3,12200,3
99996,99996,201906,11,서울특별시,1165,서초구,11650520,서초2동,30,생활,...,내국인,43,충청북도,4311,청주시,1,50대,4,50600,10
99997,99997,201906,11,서울특별시,1117,용산구,11170520,용산2가동,30,생활,...,내국인,11,서울특별시,1162,관악구,1,40대,2,38640,7

In [74]:
cvs_df['AMT'].sum() # 전체 편의점 소비

np.int64(7299184098)

In [75]:
gangnam_df = bccard_df[bccard_df['CTY_RGN_NM'] == '강남구'] # 강남구 데이터만 추출
gangnam_df

,Unnamed: 0,REG_YYMM,MEGA_CTY_NO,MEGA_CTY_NM,CTY_RGN_NO,CTY_RGN_NM,ADMI_CTY_NO,ADMI_CTY_NM,MAIN_BUZ_CODE,MAIN_BUZ_DESC,...,CSTMR_GUBUN,CSTMR_MEGA_CTY_NO,CSTMR_MEGA_CTY_NM,CSTMR_CTY_RGN_NO,CSTMR_CTY_RGN_NM,SEX_CTGO_CD,AGE_VAL,FLC,AMT,CNT
6,6,201906,11,서울특별시,1168,강남구,11680521,논현1동,30,생활,...,내국인,11,서울특별시,1150,강서구,2,20대,1,1461800,274
8,8,201906,11,서울특별시,1168,강남구,11680656,도곡2동,30,생활,...,내국인,45,전라북도,4511,전주시,2,30대,2,36909050,3465
12,12,201906,11,서울특별시,1168,강남구,11680545,압구정동,30,생활,...,내국인,11,서울특별시,1168,강남구,1,30대,3,230730,34
21,21,201906,11,서울특별시,1168,강남구,11680656,도곡2동,30,생활,...,내국인,27,대구광역시,2723,북구,2,50대,4,27159650,2559
28,28,201906,11,서울특별시,1168,강남구,11680590,삼성2동,80,음식,...,내국인,11,서울특별시,1165,서초구,2,60대 이상,5,3960400,83
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99952,99952,201906,11,서울특별시,1168,강남구,11680545,압구정동,85,유흥,...,내국인,11,서울특별시,1114,중구,2,50대,4,180000,9
99955,99955,201906,11,서울특별시,1168,강남구,11680700,세곡동,30,생활,...,내국인,41,경기도,4146,용인시,1,40대,3,61400,4
99967,99967,201906,11,서울특별시,1168,강남구,11680590,삼성2동,80,음식,...,내국인,11,서울특별시,1126,중랑구,1,30대,1,210700,14
99985,99985,201906,11,서울특별시,1168,강남구,11680630,대치4동,80,음식,...,내국인,11,서울특별시,1141,서대문구,2,40대,3,108800,6
99994,99994,201906,11,서울특별시,1168,강남구,11680545,압구정동,99,기타,...,내국인,11,서울특별시,1126,중랑구,1,30대,2,1432000,3

In [76]:
gangnam_df['AMT'].sum() # 강남구 전체 소비액

np.int64(35535648502)

In [77]:
gangnam_cvs = bccard_df[(bccard_df['CTY_RGN_NM'] == '강남구') & (bccard_df['TP_BUZ_NO'] == 4010)] # 강남구에 있는 편의점 데이터만 추출(두 조건 동시 만족)
gangnam_cvs

,Unnamed: 0,REG_YYMM,MEGA_CTY_NO,MEGA_CTY_NM,CTY_RGN_NO,CTY_RGN_NM,ADMI_CTY_NO,ADMI_CTY_NM,MAIN_BUZ_CODE,MAIN_BUZ_DESC,...,CSTMR_GUBUN,CSTMR_MEGA_CTY_NO,CSTMR_MEGA_CTY_NM,CSTMR_CTY_RGN_NO,CSTMR_CTY_RGN_NM,SEX_CTGO_CD,AGE_VAL,FLC,AMT,CNT
6,6,201906,11,서울특별시,1168,강남구,11680521,논현1동,30,생활,...,내국인,11,서울특별시,1150,강서구,2,20대,1,1461800,274
12,12,201906,11,서울특별시,1168,강남구,11680545,압구정동,30,생활,...,내국인,11,서울특별시,1168,강남구,1,30대,3,230730,34
60,60,201906,11,서울특별시,1168,강남구,11680640,역삼1동,30,생활,...,내국인,41,경기도,4115,의정부시,1,40대,3,1059540,195
64,64,201906,11,서울특별시,1168,강남구,11680521,논현1동,30,생활,...,내국인,41,경기도,4113,성남시,1,40대,3,2026160,320
97,97,201906,11,서울특별시,1168,강남구,11680750,수서동,30,생활,...,내국인,11,서울특별시,1168,강남구,1,30대,2,12673800,2279
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99701,99701,201906,11,서울특별시,1168,강남구,11680650,역삼2동,30,생활,...,내국인,11,서울특별시,1168,강남구,1,40대,3,23756070,3203
99772,99772,201906,11,서울특별시,1168,강남구,11680630,대치4동,30,생활,...,내국인,11,서울특별시,1135,노원구,1,40대,2,184620,29
99827,99827,201906,11,서울특별시,1168,강남구,11680720,일원본동,30,생활,...,내국인,45,전라북도,4513,군산시,1,60대 이상,5,110300,19
99865,99865,201906,11,서울특별시,1168,강남구,11680640,역삼1동,30,생활,...,내국인,26,부산광역시,2671,기장군,1,30대,2,183520,22
99903,99903,201906,11,서울특별시,1168,강남구,11680640,역삼1동,30,생활,...,내국인,11,서울특별시,1132,도봉구,1,40대,4,89960,17

In [78]:
gangnam_cvs['AMT'].sum() # 강남구 편의점 총 소비액

np.int64(707275140)

In [81]:
resident_amt = gangnam_cvs[gangnam_cvs['CSTMR_CTY_RGN_NM'] == '강남구']['AMT'].sum() # 강남구 편의점 소비액 중 강남구 거주자와 비거주자의 소비액 비교
resident_amt # 강남구 편의점 (깅남구 거주자) 소비액

np.int64(288379890)

In [83]:
non_resident_amt = gangnam_cvs[gangnam_cvs['CSTMR_CTY_RGN_NM'] != '강남구']['AMT'].sum() # 강남구 편의점 소비액 중 강남구 거주자와 비거주자의 소비액 비교
non_resident_amt # 강남구 편의점 (비거주자) 소비액

np.int64(418895250)